from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

from xtb_bot.worker.config_runtime import WorkerConfigRuntime
from xtb_bot.worker.diagnostics import WorkerDiagnosticsRuntime
from xtb_bot.worker.dynamic_exit_runtime import WorkerDynamicExitRuntime
from xtb_bot.worker.entry_planner import WorkerEntryPlanner
from xtb_bot.worker.execution_quality import WorkerExecutionQualityRuntime
from xtb_bot.worker.health import WorkerHealthMonitor
from xtb_bot.worker.history import WorkerHistoryRuntime
from xtb_bot.worker.multi_strategy import WorkerMultiStrategyRuntime
from xtb_bot.worker.orders import WorkerOrderManager
from xtb_bot.worker.price_guard_runtime import WorkerPriceGuardRuntime
from xtb_bot.worker.price_runtime import WorkerPriceRuntime
from xtb_bot.worker.reconcile import WorkerReconcileManager
from xtb_bot.worker.recovery import WorkerRecoveryManager
from xtb_bot.worker.risk import WorkerRiskEvaluator
from xtb_bot.worker.signal_runtime import WorkerSignalRuntime
from xtb_bot.worker.strategy_params import WorkerStrategyParamRuntime
from xtb_bot.worker.symbol_runtime import WorkerSymbolRuntime
from xtb_bot.worker.symbol_spec import WorkerSymbolSpecRuntime
from xtb_bot.worker.trailing_runtime import WorkerTrailingRuntime
from xtb_bot.worker.value_runtime import WorkerValueRuntime


@dataclass(frozen=True)
class WorkerMethodBindingSpec:
    method_name: str
    target_kind: str
    target_ref: str
    target_method: str


_CLASS_TARGETS = {
    'WorkerConfigRuntime': WorkerConfigRuntime,
    'WorkerDiagnosticsRuntime': WorkerDiagnosticsRuntime,
    'WorkerDynamicExitRuntime': WorkerDynamicExitRuntime,
    'WorkerEntryPlanner': WorkerEntryPlanner,
    'WorkerExecutionQualityRuntime': WorkerExecutionQualityRuntime,
    'WorkerHealthMonitor': WorkerHealthMonitor,
    'WorkerHistoryRuntime': WorkerHistoryRuntime,
    'WorkerMultiStrategyRuntime': WorkerMultiStrategyRuntime,
    'WorkerOrderManager': WorkerOrderManager,
    'WorkerPriceGuardRuntime': WorkerPriceGuardRuntime,
    'WorkerPriceRuntime': WorkerPriceRuntime,
    'WorkerReconcileManager': WorkerReconcileManager,
    'WorkerRecoveryManager': WorkerRecoveryManager,
    'WorkerRiskEvaluator': WorkerRiskEvaluator,
    'WorkerSignalRuntime': WorkerSignalRuntime,
    'WorkerStrategyParamRuntime': WorkerStrategyParamRuntime,
    'WorkerSymbolRuntime': WorkerSymbolRuntime,
    'WorkerSymbolSpecRuntime': WorkerSymbolSpecRuntime,
    'WorkerTrailingRuntime': WorkerTrailingRuntime,
    'WorkerValueRuntime': WorkerValueRuntime,
}


_METHOD_SPECS = {
    '_activate_operational_guard': WorkerMethodBindingSpec(method_name='_activate_operational_guard', target_kind='instance', target_ref='_risk_evaluator', target_method='activate_operational_guard'),
    '_activate_reject_entry_cooldown': WorkerMethodBindingSpec(method_name='_activate_reject_entry_cooldown', target_kind='instance', target_ref='_risk_evaluator', target_method='activate_reject_entry_cooldown'),
    '_adaptive_trailing_candidate_stop': WorkerMethodBindingSpec(method_name='_adaptive_trailing_candidate_stop', target_kind='instance', target_ref='_trailing_runtime', target_method='adaptive_trailing_candidate_stop'),
    '_adaptive_trailing_entry_extreme_abs_from_metadata': WorkerMethodBindingSpec(method_name='_adaptive_trailing_entry_extreme_abs_from_metadata', target_kind='instance', target_ref='_trailing_runtime', target_method='adaptive_trailing_entry_extreme_abs_from_metadata'),
    '_adaptive_trailing_family_from_metadata': WorkerMethodBindingSpec(method_name='_adaptive_trailing_family_from_metadata', target_kind='instance', target_ref='_trailing_runtime', target_method='adaptive_trailing_family_from_metadata'),
    '_adaptive_trailing_heat': WorkerMethodBindingSpec(method_name='_adaptive_trailing_heat', target_kind='instance', target_ref='_trailing_runtime', target_method='adaptive_trailing_heat'),
    '_adaptive_trailing_mean_reversion_heat': WorkerMethodBindingSpec(method_name='_adaptive_trailing_mean_reversion_heat', target_kind='instance', target_ref='_trailing_runtime', target_method='adaptive_trailing_mean_reversion_heat'),
    '_adaptive_trailing_override_context': WorkerMethodBindingSpec(method_name='_adaptive_trailing_override_context', target_kind='instance', target_ref='_trailing_runtime', target_method='adaptive_trailing_override_context'),
    '_adaptive_trailing_trend_heat': WorkerMethodBindingSpec(method_name='_adaptive_trailing_trend_heat', target_kind='instance', target_ref='_trailing_runtime', target_method='adaptive_trailing_trend_heat'),
    '_adopt_symbol_spec_for_entry': WorkerMethodBindingSpec(method_name='_adopt_symbol_spec_for_entry', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='adopt_symbol_spec_for_entry'),
    '_allow_risk_reducing_action_after_lease_revocation': WorkerMethodBindingSpec(method_name='_allow_risk_reducing_action_after_lease_revocation', target_kind='instance', target_ref='_lifecycle_manager', target_method='allow_risk_reducing_action_after_lease_revocation'),
    '_apply_breakeven_protection': WorkerMethodBindingSpec(method_name='_apply_breakeven_protection', target_kind='instance', target_ref='_order_manager', target_method='apply_breakeven_protection'),
    '_apply_broker_min_stop_distance_guard': WorkerMethodBindingSpec(method_name='_apply_broker_min_stop_distance_guard', target_kind='instance', target_ref='_price_guard_runtime', target_method='apply_broker_min_stop_distance_guard'),
    '_apply_broker_open_level_guard': WorkerMethodBindingSpec(method_name='_apply_broker_open_level_guard', target_kind='instance', target_ref='_price_guard_runtime', target_method='apply_broker_open_level_guard'),
    '_apply_broker_open_level_guard_for_spec': WorkerMethodBindingSpec(method_name='_apply_broker_open_level_guard_for_spec', target_kind='instance', target_ref='_price_guard_runtime', target_method='apply_broker_open_level_guard_for_spec'),
    '_apply_broker_tick_value_calibration': WorkerMethodBindingSpec(method_name='_apply_broker_tick_value_calibration', target_kind='instance', target_ref='_entry_planner', target_method='apply_broker_tick_value_calibration'),
    '_apply_multi_strategy_scale_out_allocation': WorkerMethodBindingSpec(method_name='_apply_multi_strategy_scale_out_allocation', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='apply_scale_out_allocation'),
    '_apply_multi_strategy_scale_out_offset': WorkerMethodBindingSpec(method_name='_apply_multi_strategy_scale_out_offset', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='apply_scale_out_offset'),
    '_apply_news_filter': WorkerMethodBindingSpec(method_name='_apply_news_filter', target_kind='instance', target_ref='_diagnostics_runtime', target_method='apply_news_filter'),
    '_apply_operational_guard_risk_reduction': WorkerMethodBindingSpec(method_name='_apply_operational_guard_risk_reduction', target_kind='instance', target_ref='_risk_evaluator', target_method='apply_operational_guard_risk_reduction'),
    '_apply_position_strategy_metadata': WorkerMethodBindingSpec(method_name='_apply_position_strategy_metadata', target_kind='instance', target_ref='_trade_metadata_runtime', target_method='apply_position_strategy_metadata'),
    '_apply_trailing_stop': WorkerMethodBindingSpec(method_name='_apply_trailing_stop', target_kind='instance', target_ref='_order_manager', target_method='apply_trailing_stop'),
    '_append_spread_sample': WorkerMethodBindingSpec(method_name='_append_spread_sample', target_kind='instance', target_ref='_risk_evaluator', target_method='append_spread_sample'),
    '_arm_pending_close_verification': WorkerMethodBindingSpec(method_name='_arm_pending_close_verification', target_kind='instance', target_ref='_reconcile_manager', target_method='arm_pending_close_verification'),
    '_attempt_pending_missing_position_reconciliation': WorkerMethodBindingSpec(method_name='_attempt_pending_missing_position_reconciliation', target_kind='instance', target_ref='_reconcile_manager', target_method='attempt_pending_missing_position_reconciliation'),
    '_base_strategy_label': WorkerMethodBindingSpec(method_name='_base_strategy_label', target_kind='instance', target_ref='_strategy_param_runtime', target_method='base_strategy_label'),
    '_breakeven_lock_candidate_stop': WorkerMethodBindingSpec(method_name='_breakeven_lock_candidate_stop', target_kind='instance', target_ref='_protective_runtime', target_method='breakeven_lock_candidate_stop'),
    '_broker_account_currency_code': WorkerMethodBindingSpec(method_name='_broker_account_currency_code', target_kind='instance', target_ref='_value_runtime', target_method='broker_account_currency_code'),
    '_broker_get_symbol_spec': WorkerMethodBindingSpec(method_name='_broker_get_symbol_spec', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='broker_get_symbol_spec'),
    '_broker_get_symbol_spec_candidates_for_entry': WorkerMethodBindingSpec(method_name='_broker_get_symbol_spec_candidates_for_entry', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='broker_get_symbol_spec_candidates_for_entry'),
    '_broker_get_symbol_spec_for_epic': WorkerMethodBindingSpec(method_name='_broker_get_symbol_spec_for_epic', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='broker_get_symbol_spec_for_epic'),
    '_broker_min_stop_distance_price': WorkerMethodBindingSpec(method_name='_broker_min_stop_distance_price', target_kind='instance', target_ref='_price_guard_runtime', target_method='broker_min_stop_distance_price'),
    '_broker_public_api_backoff_remaining_sec': WorkerMethodBindingSpec(method_name='_broker_public_api_backoff_remaining_sec', target_kind='instance', target_ref='_recovery_manager', target_method='broker_public_api_backoff_remaining_sec'),
    '_build_candle_history_context': WorkerMethodBindingSpec(method_name='_build_candle_history_context', target_kind='instance', target_ref='_history_runtime', target_method='build_candle_history_context'),
    '_build_multi_strategy_signal': WorkerMethodBindingSpec(method_name='_build_multi_strategy_signal', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='build_signal'),
    '_build_sl_tp': WorkerMethodBindingSpec(method_name='_build_sl_tp', target_kind='instance', target_ref='_entry_planner', target_method='build_sl_tp'),
    '_build_sl_tp_for_spec': WorkerMethodBindingSpec(method_name='_build_sl_tp_for_spec', target_kind='instance', target_ref='_entry_planner', target_method='build_sl_tp_for_spec'),
    '_build_strategy_context': WorkerMethodBindingSpec(method_name='_build_strategy_context', target_kind='instance', target_ref='_signal_runtime', target_method='build_strategy_context'),
    '_build_strategy_context_for_strategy': WorkerMethodBindingSpec(method_name='_build_strategy_context_for_strategy', target_kind='instance', target_ref='_signal_runtime', target_method='build_strategy_context_for_strategy'),
    '_cache_price_sample': WorkerMethodBindingSpec(method_name='_cache_price_sample', target_kind='instance', target_ref='_history_runtime', target_method='cache_price_sample'),
    '_cache_symbol_pip_size': WorkerMethodBindingSpec(method_name='_cache_symbol_pip_size', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='cache_symbol_pip_size'),
    '_calculate_pnl': WorkerMethodBindingSpec(method_name='_calculate_pnl', target_kind='instance', target_ref='_value_runtime', target_method='calculate_pnl'),
    '_clear_continuation_reentry_block': WorkerMethodBindingSpec(method_name='_clear_continuation_reentry_block', target_kind='instance', target_ref='_risk_evaluator', target_method='clear_continuation_reentry_block'),
    '_clear_entry_signal_persistence_state': WorkerMethodBindingSpec(method_name='_clear_entry_signal_persistence_state', target_kind='instance', target_ref='_risk_evaluator', target_method='clear_entry_signal_persistence_state'),
    '_clear_pending_close_verification': WorkerMethodBindingSpec(method_name='_clear_pending_close_verification', target_kind='instance', target_ref='_reconcile_manager', target_method='clear_pending_close_verification'),
    '_clear_pending_missing_position_reconciliation': WorkerMethodBindingSpec(method_name='_clear_pending_missing_position_reconciliation', target_kind='instance', target_ref='_reconcile_manager', target_method='clear_pending_missing_position_reconciliation'),
    '_clear_persisted_trailing_override': WorkerMethodBindingSpec(method_name='_clear_persisted_trailing_override', target_kind='instance', target_ref='_order_manager', target_method='clear_persisted_trailing_override'),
    '_clear_position_runtime_state': WorkerMethodBindingSpec(method_name='_clear_position_runtime_state', target_kind='instance', target_ref='_order_manager', target_method='clear_position_runtime_state'),
    '_close_position': WorkerMethodBindingSpec(method_name='_close_position', target_kind='instance', target_ref='_order_manager', target_method='close_position'),
    '_close_verification_retry_interval_sec': WorkerMethodBindingSpec(method_name='_close_verification_retry_interval_sec', target_kind='instance', target_ref='_reconcile_manager', target_method='close_verification_retry_interval_sec'),
    '_confidence_allows_open': WorkerMethodBindingSpec(method_name='_confidence_allows_open', target_kind='instance', target_ref='_risk_evaluator', target_method='confidence_allows_open'),
    '_connectivity_allows_open': WorkerMethodBindingSpec(method_name='_connectivity_allows_open', target_kind='instance', target_ref='_health_monitor', target_method='connectivity_allows_open'),
    '_connectivity_status_allows_trading': WorkerMethodBindingSpec(method_name='_connectivity_status_allows_trading', target_kind='instance', target_ref='_health_monitor', target_method='connectivity_status_allows_trading'),
    '_context_pip_size': WorkerMethodBindingSpec(method_name='_context_pip_size', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='context_pip_size'),
    '_continuation_reentry_allows_open': WorkerMethodBindingSpec(method_name='_continuation_reentry_allows_open', target_kind='instance', target_ref='_risk_evaluator', target_method='continuation_reentry_allows_open'),
    '_contract_multiplier_fallback': WorkerMethodBindingSpec(method_name='_contract_multiplier_fallback', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='contract_multiplier_fallback'),
    '_cooldown_allows_open': WorkerMethodBindingSpec(method_name='_cooldown_allows_open', target_kind='instance', target_ref='_risk_evaluator', target_method='cooldown_allows_open'),
    '_cooldown_duration_for_outcome': WorkerMethodBindingSpec(method_name='_cooldown_duration_for_outcome', target_kind='instance', target_ref='_risk_evaluator', target_method='cooldown_duration_for_outcome'),
    '_currency_conversion_rate': WorkerMethodBindingSpec(method_name='_currency_conversion_rate', target_kind='instance', target_ref='_value_runtime', target_method='currency_conversion_rate'),
    '_current_multi_strategy_emergency_worker_error': WorkerMethodBindingSpec(method_name='_current_multi_strategy_emergency_worker_error', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='current_emergency_worker_error'),
    '_current_real_position_virtual_lots': WorkerMethodBindingSpec(method_name='_current_real_position_virtual_lots', target_kind='instance', target_ref='_signal_runtime', target_method='current_real_position_virtual_lots'),
    '_derived_confidence_hard_floor_for_signal': WorkerMethodBindingSpec(method_name='_derived_confidence_hard_floor_for_signal', target_kind='instance', target_ref='_risk_evaluator', target_method='derived_confidence_hard_floor_for_signal'),
    '_disable_symbol': WorkerMethodBindingSpec(method_name='_disable_symbol', target_kind='instance', target_ref='_recovery_manager', target_method='disable_symbol'),
    '_early_loss_cut_allowed': WorkerMethodBindingSpec(method_name='_early_loss_cut_allowed', target_kind='instance', target_ref='_protective_runtime', target_method='early_loss_cut_allowed'),
    '_effective_confidence_hard_floor_for_signal': WorkerMethodBindingSpec(method_name='_effective_confidence_hard_floor_for_signal', target_kind='instance', target_ref='_risk_evaluator', target_method='effective_confidence_hard_floor_for_signal'),
    '_effective_entry_component_from_signal': WorkerMethodBindingSpec(method_name='_effective_entry_component_from_signal', target_kind='instance', target_ref='_trade_metadata_runtime', target_method='effective_entry_component_from_signal'),
    '_effective_entry_signal_from_signal': WorkerMethodBindingSpec(method_name='_effective_entry_signal_from_signal', target_kind='instance', target_ref='_trade_metadata_runtime', target_method='effective_entry_signal_from_signal'),
    '_effective_entry_strategy_from_signal': WorkerMethodBindingSpec(method_name='_effective_entry_strategy_from_signal', target_kind='instance', target_ref='_trade_metadata_runtime', target_method='effective_entry_strategy_from_signal'),
    '_effective_exit_metadata_from_reason': WorkerMethodBindingSpec(method_name='_effective_exit_metadata_from_reason', target_kind='instance', target_ref='_trade_metadata_runtime', target_method='effective_exit_metadata_from_reason'),
    '_effective_index_hybrid_regime_from_signal': WorkerMethodBindingSpec(method_name='_effective_index_hybrid_regime_from_signal', target_kind='instance', target_ref='_risk_evaluator', target_method='effective_index_hybrid_regime_from_signal'),
    '_effective_min_confidence_for_signal': WorkerMethodBindingSpec(method_name='_effective_min_confidence_for_signal', target_kind='instance', target_ref='_risk_evaluator', target_method='effective_min_confidence_for_signal'),
    '_effective_signal_min_history': WorkerMethodBindingSpec(method_name='_effective_signal_min_history', target_kind='instance', target_ref='_diagnostics_runtime', target_method='effective_signal_min_history'),
    '_effective_trailing_settings': WorkerMethodBindingSpec(method_name='_effective_trailing_settings', target_kind='instance', target_ref='_trailing_runtime', target_method='effective_trailing_settings'),
    '_entry_news_filter_allows_open': WorkerMethodBindingSpec(method_name='_entry_news_filter_allows_open', target_kind='instance', target_ref='_diagnostics_runtime', target_method='entry_news_filter_allows_open'),
    '_entry_signal_persistence_allows_open': WorkerMethodBindingSpec(method_name='_entry_signal_persistence_allows_open', target_kind='instance', target_ref='_risk_evaluator', target_method='entry_signal_persistence_allows_open'),
    '_entry_signal_persistence_requirements': WorkerMethodBindingSpec(method_name='_entry_signal_persistence_requirements', target_kind='instance', target_ref='_risk_evaluator', target_method='entry_signal_persistence_requirements'),
    '_entry_signal_persistence_signature_for_signal': WorkerMethodBindingSpec(method_name='_entry_signal_persistence_signature_for_signal', target_kind='instance', target_ref='_risk_evaluator', target_method='entry_signal_persistence_signature_for_signal'),
    '_entry_spike_guard_block_payload': WorkerMethodBindingSpec(method_name='_entry_spike_guard_block_payload', target_kind='instance', target_ref='_risk_evaluator', target_method='entry_spike_guard_block_payload'),
    '_entry_tick_age_allows_open': WorkerMethodBindingSpec(method_name='_entry_tick_age_allows_open', target_kind='instance', target_ref='_risk_evaluator', target_method='entry_tick_age_allows_open'),
    '_entry_variant_affordability_key': WorkerMethodBindingSpec(method_name='_entry_variant_affordability_key', target_kind='instance', target_ref='_entry_planner', target_method='entry_variant_affordability_key'),
    '_epic_text': WorkerMethodBindingSpec(method_name='_epic_text', target_kind='instance', target_ref='_symbol_runtime', target_method='epic_text'),
    '_execution_calibrated_entry_signal': WorkerMethodBindingSpec(method_name='_execution_calibrated_entry_signal', target_kind='instance', target_ref='_execution_quality_runtime', target_method='execution_calibrated_entry_signal'),
    '_execution_pip_size': WorkerMethodBindingSpec(method_name='_execution_pip_size', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='execution_pip_size'),
    '_execution_pip_size_for_spec': WorkerMethodBindingSpec(method_name='_execution_pip_size_for_spec', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='execution_pip_size_for_spec'),
    '_fast_fail_exit_allowed': WorkerMethodBindingSpec(method_name='_fast_fail_exit_allowed', target_kind='instance', target_ref='_protective_runtime', target_method='fast_fail_exit_allowed'),
    '_fill_quality_weight_multiplier': WorkerMethodBindingSpec(method_name='_fill_quality_weight_multiplier', target_kind='instance', target_ref='_execution_quality_runtime', target_method='fill_quality_weight_multiplier'),
    '_finalize_position_close': WorkerMethodBindingSpec(method_name='_finalize_position_close', target_kind='instance', target_ref='_order_manager', target_method='finalize_position_close'),
    '_fresh_reversal_grace_blocks_exit': WorkerMethodBindingSpec(method_name='_fresh_reversal_grace_blocks_exit', target_kind='instance', target_ref='_protective_runtime', target_method='fresh_reversal_grace_blocks_exit'),
    '_generate_signal': WorkerMethodBindingSpec(method_name='_generate_signal', target_kind='instance', target_ref='_signal_runtime', target_method='generate_signal'),
    '_generic_protective_dynamic_exit_reason': WorkerMethodBindingSpec(method_name='_generic_protective_dynamic_exit_reason', target_kind='instance', target_ref='_dynamic_exit_runtime', target_method='generic_protective_dynamic_exit_reason'),
    '_get_account_snapshot_cached': WorkerMethodBindingSpec(method_name='_get_account_snapshot_cached', target_kind='instance', target_ref='_runtime_state_manager', target_method='get_account_snapshot_cached'),
    '_get_broker_close_sync': WorkerMethodBindingSpec(method_name='_get_broker_close_sync', target_kind='instance', target_ref='_reconcile_manager', target_method='get_broker_close_sync'),
    '_get_broker_open_sync': WorkerMethodBindingSpec(method_name='_get_broker_open_sync', target_kind='instance', target_ref='_reconcile_manager', target_method='get_broker_open_sync'),
    '_get_position_trailing_override': WorkerMethodBindingSpec(method_name='_get_position_trailing_override', target_kind='instance', target_ref='_order_manager', target_method='get_position_trailing_override'),
    '_handle_active_position_without_fresh_tick': WorkerMethodBindingSpec(method_name='_handle_active_position_without_fresh_tick', target_kind='instance', target_ref='_order_manager', target_method='handle_active_position_without_fresh_tick'),
    '_handle_allowance_backoff_error': WorkerMethodBindingSpec(method_name='_handle_allowance_backoff_error', target_kind='instance', target_ref='_recovery_manager', target_method='handle_allowance_backoff_error'),
    '_handle_broker_error_exception': WorkerMethodBindingSpec(method_name='_handle_broker_error_exception', target_kind='instance', target_ref='_recovery_manager', target_method='handle_broker_exception'),
    '_handle_db_first_symbol_spec_cache_miss': WorkerMethodBindingSpec(method_name='_handle_db_first_symbol_spec_cache_miss', target_kind='instance', target_ref='_recovery_manager', target_method='handle_db_first_symbol_spec_cache_miss'),
    '_handle_db_first_tick_cache_miss': WorkerMethodBindingSpec(method_name='_handle_db_first_tick_cache_miss', target_kind='instance', target_ref='_recovery_manager', target_method='handle_db_first_tick_cache_miss'),
    '_handle_missing_broker_position_error': WorkerMethodBindingSpec(method_name='_handle_missing_broker_position_error', target_kind='instance', target_ref='_reconcile_manager', target_method='handle_missing_broker_position_error'),
    '_hold_reason_metadata_payload': WorkerMethodBindingSpec(method_name='_hold_reason_metadata_payload', target_kind='instance', target_ref='_diagnostics_runtime', target_method='hold_reason_metadata_payload'),
    '_index_trend_reversal_grace_blocks_exit': WorkerMethodBindingSpec(method_name='_index_trend_reversal_grace_blocks_exit', target_kind='instance', target_ref='_protective_runtime', target_method='index_trend_reversal_grace_blocks_exit'),
    '_index_trend_structure_allows_open': WorkerMethodBindingSpec(method_name='_index_trend_structure_allows_open', target_kind='instance', target_ref='_risk_evaluator', target_method='index_trend_structure_allows_open'),
    '_infer_missing_position_close': WorkerMethodBindingSpec(method_name='_infer_missing_position_close', target_kind='instance', target_ref='_reconcile_manager', target_method='infer_missing_position_close'),
    '_initialize_multi_strategy_runtime': WorkerMethodBindingSpec(method_name='_initialize_multi_strategy_runtime', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='initialize_runtime'),
    '_is_ambiguous_ig_tick_value_spec': WorkerMethodBindingSpec(method_name='_is_ambiguous_ig_tick_value_spec', target_kind='instance', target_ref='_entry_planner', target_method='is_ambiguous_ig_tick_value_spec'),
    '_is_commodity_symbol': WorkerMethodBindingSpec(method_name='_is_commodity_symbol', target_kind='instance', target_ref='_symbol_runtime', target_method='is_commodity_symbol'),
    '_is_connectivity_non_blocking': WorkerMethodBindingSpec(method_name='_is_connectivity_non_blocking', target_kind='instance', target_ref='_health_monitor', target_method='is_connectivity_non_blocking'),
    '_is_crypto_symbol': WorkerMethodBindingSpec(method_name='_is_crypto_symbol', target_kind='instance', target_ref='_symbol_runtime', target_method='is_crypto_symbol'),
    '_is_fx_symbol': WorkerMethodBindingSpec(method_name='_is_fx_symbol', target_kind='instance', target_ref='_symbol_runtime', target_method='is_fx_symbol'),
    '_is_index_hybrid_trend_entry_signal': WorkerMethodBindingSpec(method_name='_is_index_hybrid_trend_entry_signal', target_kind='instance', target_ref='_risk_evaluator', target_method='is_index_hybrid_trend_entry_signal'),
    '_is_index_symbol': WorkerMethodBindingSpec(method_name='_is_index_symbol', target_kind='instance', target_ref='_symbol_runtime', target_method='is_index_symbol'),
    '_is_non_fx_cfd_symbol': WorkerMethodBindingSpec(method_name='_is_non_fx_cfd_symbol', target_kind='instance', target_ref='_symbol_runtime', target_method='is_non_fx_cfd_symbol'),
    '_latest_price': WorkerMethodBindingSpec(method_name='_latest_price', target_kind='instance', target_ref='_runtime_state_manager', target_method='latest_price'),
    '_latest_spread_pips': WorkerMethodBindingSpec(method_name='_latest_spread_pips', target_kind='instance', target_ref='_risk_evaluator', target_method='latest_spread_pips'),
    '_load_db_first_tick': WorkerMethodBindingSpec(method_name='_load_db_first_tick', target_kind='instance', target_ref='_data_access_runtime', target_method='load_db_first_tick'),
    '_load_direct_account_snapshot_fallback': WorkerMethodBindingSpec(method_name='_load_direct_account_snapshot_fallback', target_kind='instance', target_ref='_data_access_runtime', target_method='load_direct_account_snapshot_fallback'),
    '_load_direct_tick_for_active_position_fallback': WorkerMethodBindingSpec(method_name='_load_direct_tick_for_active_position_fallback', target_kind='instance', target_ref='_data_access_runtime', target_method='load_direct_tick_for_active_position_fallback'),
    '_load_direct_tick_for_entry_fallback': WorkerMethodBindingSpec(method_name='_load_direct_tick_for_entry_fallback', target_kind='instance', target_ref='_data_access_runtime', target_method='load_direct_tick_for_entry_fallback'),
    '_load_persisted_trailing_override_for_position': WorkerMethodBindingSpec(method_name='_load_persisted_trailing_override_for_position', target_kind='instance', target_ref='_order_manager', target_method='load_persisted_trailing_override_for_position'),
    '_load_symbol_spec': WorkerMethodBindingSpec(method_name='_load_symbol_spec', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='load_symbol_spec'),
    '_local_allowance_backoff_remaining_sec': WorkerMethodBindingSpec(method_name='_local_allowance_backoff_remaining_sec', target_kind='instance', target_ref='_recovery_manager', target_method='local_allowance_backoff_remaining_sec'),
    '_log_effective_entry_gates': WorkerMethodBindingSpec(method_name='_log_effective_entry_gates', target_kind='instance', target_ref='_config_runtime', target_method='log_effective_entry_gates'),
    '_log_strategy_param_hints': WorkerMethodBindingSpec(method_name='_log_strategy_param_hints', target_kind='instance', target_ref='_config_runtime', target_method='log_strategy_param_hints'),
    '_manual_close_sync_interval_for_position': WorkerMethodBindingSpec(method_name='_manual_close_sync_interval_for_position', target_kind='instance', target_ref='_reconcile_manager', target_method='manual_close_sync_interval_for_position'),
    '_mark_news_event_handled': WorkerMethodBindingSpec(method_name='_mark_news_event_handled', target_kind='instance', target_ref='_diagnostics_runtime', target_method='mark_news_event_handled'),
    '_maybe_adapt_mean_breakout_buffer_after_entry_slippage': WorkerMethodBindingSpec(method_name='_maybe_adapt_mean_breakout_buffer_after_entry_slippage', target_kind='instance', target_ref='_execution_quality_runtime', target_method='maybe_adapt_mean_breakout_buffer_after_entry_slippage'),
    '_maybe_apply_partial_take_profit': WorkerMethodBindingSpec(method_name='_maybe_apply_partial_take_profit', target_kind='instance', target_ref='_order_manager', target_method='maybe_apply_partial_take_profit'),
    '_maybe_execute_pending_close_retry': WorkerMethodBindingSpec(method_name='_maybe_execute_pending_close_retry', target_kind='instance', target_ref='_order_manager', target_method='maybe_execute_pending_close_retry'),
    '_maybe_mark_symbol_guaranteed_stop_required_after_slippage': WorkerMethodBindingSpec(method_name='_maybe_mark_symbol_guaranteed_stop_required_after_slippage', target_kind='instance', target_ref='_execution_quality_runtime', target_method='maybe_mark_symbol_guaranteed_stop_required_after_slippage'),
    '_maybe_reconcile_execution_manual_close': WorkerMethodBindingSpec(method_name='_maybe_reconcile_execution_manual_close', target_kind='instance', target_ref='_reconcile_manager', target_method='maybe_reconcile_execution_manual_close'),
    '_maybe_record_broker_tick_value_calibration': WorkerMethodBindingSpec(method_name='_maybe_record_broker_tick_value_calibration', target_kind='instance', target_ref='_entry_planner', target_method='maybe_record_broker_tick_value_calibration'),
    '_maybe_record_hold_reason': WorkerMethodBindingSpec(method_name='_maybe_record_hold_reason', target_kind='instance', target_ref='_diagnostics_runtime', target_method='maybe_record_hold_reason'),
    '_maybe_record_indicator_debug': WorkerMethodBindingSpec(method_name='_maybe_record_indicator_debug', target_kind='instance', target_ref='_diagnostics_runtime', target_method='maybe_record_indicator_debug'),
    '_maybe_record_multi_strategy_emergency': WorkerMethodBindingSpec(method_name='_maybe_record_multi_strategy_emergency', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='maybe_record_emergency'),
    '_maybe_record_stream_usage_metrics': WorkerMethodBindingSpec(method_name='_maybe_record_stream_usage_metrics', target_kind='instance', target_ref='_health_monitor', target_method='maybe_record_stream_usage_metrics'),
    '_maybe_record_trend_hold_summary': WorkerMethodBindingSpec(method_name='_maybe_record_trend_hold_summary', target_kind='instance', target_ref='_diagnostics_runtime', target_method='maybe_record_trend_hold_summary'),
    '_maybe_retry_with_more_affordable_entry_variant': WorkerMethodBindingSpec(method_name='_maybe_retry_with_more_affordable_entry_variant', target_kind='instance', target_ref='_entry_planner', target_method='maybe_retry_with_more_affordable_entry_variant'),
    '_metadata_trend_invalidation': WorkerMethodBindingSpec(method_name='_metadata_trend_invalidation', target_kind='instance', target_ref='_dynamic_exit_runtime', target_method='metadata_trend_invalidation'),
    '_micro_chop_cooldown_payload': WorkerMethodBindingSpec(method_name='_micro_chop_cooldown_payload', target_kind='instance', target_ref='_risk_evaluator', target_method='micro_chop_cooldown_payload'),
    '_multi_component_strategy_from_metadata': WorkerMethodBindingSpec(method_name='_multi_component_strategy_from_metadata', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='multi_component_strategy_from_metadata'),
    '_multi_component_support_metrics': WorkerMethodBindingSpec(method_name='_multi_component_support_metrics', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='multi_component_support_metrics'),
    '_multi_strategy_component_family': WorkerMethodBindingSpec(method_name='_multi_strategy_component_family', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='component_family'),
    '_multi_strategy_component_hold_reason_summary': WorkerMethodBindingSpec(method_name='_multi_strategy_component_hold_reason_summary', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='component_hold_reason_summary'),
    '_multi_strategy_component_runtime_name': WorkerMethodBindingSpec(method_name='_multi_strategy_component_runtime_name', target_kind='instance', target_ref='_strategy_param_runtime', target_method='multi_strategy_component_runtime_name'),
    '_multi_strategy_emergency_exit_reason': WorkerMethodBindingSpec(method_name='_multi_strategy_emergency_exit_reason', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='emergency_exit_reason'),
    '_multi_strategy_hold_reason': WorkerMethodBindingSpec(method_name='_multi_strategy_hold_reason', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='hold_reason'),
    '_multi_strategy_regime_multipliers': WorkerMethodBindingSpec(method_name='_multi_strategy_regime_multipliers', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='regime_multipliers'),
    '_multi_strategy_runtime_health': WorkerMethodBindingSpec(method_name='_multi_strategy_runtime_health', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='runtime_health'),
    '_multi_strategy_symbol_asset_class': WorkerMethodBindingSpec(method_name='_multi_strategy_symbol_asset_class', target_kind='instance', target_ref='_symbol_runtime', target_method='multi_strategy_symbol_asset_class'),
    '_next_wait_duration': WorkerMethodBindingSpec(method_name='_next_wait_duration', target_kind='instance', target_ref='_runtime_state_manager', target_method='next_wait_duration'),
    '_normalize_pnl_to_account_currency': WorkerMethodBindingSpec(method_name='_normalize_pnl_to_account_currency', target_kind='instance', target_ref='_value_runtime', target_method='normalize_pnl_to_account_currency'),
    '_normalize_price': WorkerMethodBindingSpec(method_name='_normalize_price', target_kind='instance', target_ref='_price_runtime', target_method='normalize_price'),
    '_normalize_price_ceil': WorkerMethodBindingSpec(method_name='_normalize_price_ceil', target_kind='instance', target_ref='_price_runtime', target_method='normalize_price_ceil'),
    '_normalize_price_floor': WorkerMethodBindingSpec(method_name='_normalize_price_floor', target_kind='instance', target_ref='_price_runtime', target_method='normalize_price_floor'),
    '_normalize_tick_timestamp_for_history': WorkerMethodBindingSpec(method_name='_normalize_tick_timestamp_for_history', target_kind='instance', target_ref='_history_runtime', target_method='normalize_tick_timestamp_for_history'),
    '_normalize_timestamp_seconds': WorkerMethodBindingSpec(method_name='_normalize_timestamp_seconds', target_kind='instance', target_ref='_history_runtime', target_method='normalize_timestamp_seconds'),
    '_normalize_volume': WorkerMethodBindingSpec(method_name='_normalize_volume', target_kind='instance', target_ref='_risk_evaluator', target_method='normalize_volume'),
    '_open_position': WorkerMethodBindingSpec(method_name='_open_position', target_kind='instance', target_ref='_order_manager', target_method='open_position'),
    '_operational_guard_active': WorkerMethodBindingSpec(method_name='_operational_guard_active', target_kind='instance', target_ref='_risk_evaluator', target_method='operational_guard_active'),
    '_operational_guard_allows_open': WorkerMethodBindingSpec(method_name='_operational_guard_allows_open', target_kind='instance', target_ref='_risk_evaluator', target_method='operational_guard_allows_open'),
    '_parse_trailing_override_from_signal': WorkerMethodBindingSpec(method_name='_parse_trailing_override_from_signal', target_kind='instance', target_ref='_trailing_runtime', target_method='parse_trailing_override_from_signal'),
    '_partial_take_profit_close_volume': WorkerMethodBindingSpec(method_name='_partial_take_profit_close_volume', target_kind='instance', target_ref='_risk_evaluator', target_method='partial_take_profit_close_volume'),
    '_peak_drawdown_exit_allowed': WorkerMethodBindingSpec(method_name='_peak_drawdown_exit_allowed', target_kind='instance', target_ref='_protective_runtime', target_method='peak_drawdown_exit_allowed'),
    '_peak_stagnation_exit_allowed': WorkerMethodBindingSpec(method_name='_peak_stagnation_exit_allowed', target_kind='instance', target_ref='_protective_runtime', target_method='peak_stagnation_exit_allowed'),
    '_pending_open_conflicts_with_new_entry': WorkerMethodBindingSpec(method_name='_pending_open_conflicts_with_new_entry', target_kind='instance', target_ref='_risk_evaluator', target_method='pending_open_conflicts_with_new_entry'),
    '_persist_account_snapshot_if_due': WorkerMethodBindingSpec(method_name='_persist_account_snapshot_if_due', target_kind='instance', target_ref='_runtime_state_manager', target_method='persist_account_snapshot_if_due'),
    '_persist_entry_execution_quality': WorkerMethodBindingSpec(method_name='_persist_entry_execution_quality', target_kind='instance', target_ref='_execution_quality_runtime', target_method='persist_entry_execution_quality'),
    '_persist_exit_execution_quality': WorkerMethodBindingSpec(method_name='_persist_exit_execution_quality', target_kind='instance', target_ref='_execution_quality_runtime', target_method='persist_exit_execution_quality'),
    '_persist_position_trade_state': WorkerMethodBindingSpec(method_name='_persist_position_trade_state', target_kind='instance', target_ref='_trade_metadata_runtime', target_method='persist_position_trade_state'),
    '_persist_trade_performance_snapshot': WorkerMethodBindingSpec(method_name='_persist_trade_performance_snapshot', target_kind='instance', target_ref='_protective_runtime', target_method='persist_trade_performance_snapshot'),
    '_persist_trailing_override': WorkerMethodBindingSpec(method_name='_persist_trailing_override', target_kind='instance', target_ref='_order_manager', target_method='persist_trailing_override'),
    '_pip_size_fallback': WorkerMethodBindingSpec(method_name='_pip_size_fallback', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='pip_size_fallback'),
    '_position_adverse_move_pips': WorkerMethodBindingSpec(method_name='_position_adverse_move_pips', target_kind='instance', target_ref='_protective_runtime', target_method='position_adverse_move_pips'),
    '_position_entry_component': WorkerMethodBindingSpec(method_name='_position_entry_component', target_kind='instance', target_ref='_trade_metadata_runtime', target_method='position_entry_component'),
    '_position_entry_management_family': WorkerMethodBindingSpec(method_name='_position_entry_management_family', target_kind='instance', target_ref='_protective_runtime', target_method='position_entry_management_family'),
    '_position_entry_signal': WorkerMethodBindingSpec(method_name='_position_entry_signal', target_kind='instance', target_ref='_trade_metadata_runtime', target_method='position_entry_signal'),
    '_position_entry_strategy': WorkerMethodBindingSpec(method_name='_position_entry_strategy', target_kind='instance', target_ref='_trade_metadata_runtime', target_method='position_entry_strategy'),
    '_position_epic': WorkerMethodBindingSpec(method_name='_position_epic', target_kind='instance', target_ref='_symbol_runtime', target_method='position_epic'),
    '_position_epic_variant': WorkerMethodBindingSpec(method_name='_position_epic_variant', target_kind='instance', target_ref='_symbol_runtime', target_method='position_epic_variant'),
    '_position_favorable_move_pips': WorkerMethodBindingSpec(method_name='_position_favorable_move_pips', target_kind='instance', target_ref='_protective_runtime', target_method='position_favorable_move_pips'),
    '_position_initial_stop_pips': WorkerMethodBindingSpec(method_name='_position_initial_stop_pips', target_kind='instance', target_ref='_protective_runtime', target_method='position_initial_stop_pips'),
    '_position_management_family': WorkerMethodBindingSpec(method_name='_position_management_family', target_kind='instance', target_ref='_protective_runtime', target_method='position_management_family'),
    '_post_win_same_side_cross_allows_reentry': WorkerMethodBindingSpec(method_name='_post_win_same_side_cross_allows_reentry', target_kind='instance', target_ref='_risk_evaluator', target_method='post_win_same_side_cross_allows_reentry'),
    '_price_buffer_debug_fields': WorkerMethodBindingSpec(method_name='_price_buffer_debug_fields', target_kind='instance', target_ref='_diagnostics_runtime', target_method='price_buffer_debug_fields'),
    '_profit_lock_allowed': WorkerMethodBindingSpec(method_name='_profit_lock_allowed', target_kind='instance', target_ref='_protective_runtime', target_method='profit_lock_allowed'),
    '_protective_required_min_peak_pips': WorkerMethodBindingSpec(method_name='_protective_required_min_peak_pips', target_kind='instance', target_ref='_protective_runtime', target_method='protective_required_min_peak_pips'),
    '_prune_position_runtime_state': WorkerMethodBindingSpec(method_name='_prune_position_runtime_state', target_kind='instance', target_ref='_order_manager', target_method='prune_position_runtime_state'),
    '_publish_latest_tick': WorkerMethodBindingSpec(method_name='_publish_latest_tick', target_kind='instance', target_ref='_data_access_runtime', target_method='publish_latest_tick'),
    '_recent_fill_quality_summary': WorkerMethodBindingSpec(method_name='_recent_fill_quality_summary', target_kind='instance', target_ref='_execution_quality_runtime', target_method='recent_fill_quality_summary'),
    '_record_close_deferred_by_allowance': WorkerMethodBindingSpec(method_name='_record_close_deferred_by_allowance', target_kind='instance', target_ref='_reconcile_manager', target_method='record_close_deferred_by_allowance'),
    '_record_close_deferred_for_retry': WorkerMethodBindingSpec(method_name='_record_close_deferred_for_retry', target_kind='instance', target_ref='_reconcile_manager', target_method='record_close_deferred_for_retry'),
    '_record_close_pending_verification': WorkerMethodBindingSpec(method_name='_record_close_pending_verification', target_kind='instance', target_ref='_reconcile_manager', target_method='record_close_pending_verification'),
    '_refresh_connectivity_status': WorkerMethodBindingSpec(method_name='_refresh_connectivity_status', target_kind='instance', target_ref='_health_monitor', target_method='refresh_connectivity_status'),
    '_refresh_stale_entry_candidate': WorkerMethodBindingSpec(method_name='_refresh_stale_entry_candidate', target_kind='instance', target_ref='_history_runtime', target_method='refresh_stale_entry_candidate'),
    '_refresh_stream_health': WorkerMethodBindingSpec(method_name='_refresh_stream_health', target_kind='instance', target_ref='_health_monitor', target_method='refresh_stream_health'),
    '_refresh_symbol_pip_size_from_store': WorkerMethodBindingSpec(method_name='_refresh_symbol_pip_size_from_store', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='refresh_symbol_pip_size_from_store'),
    '_refresh_symbol_spec_after_min_order_reject': WorkerMethodBindingSpec(method_name='_refresh_symbol_spec_after_min_order_reject', target_kind='instance', target_ref='_recovery_manager', target_method='refresh_symbol_spec_after_min_order_reject'),
    '_register_broker_error': WorkerMethodBindingSpec(method_name='_register_broker_error', target_kind='instance', target_ref='_recovery_manager', target_method='register_broker_error'),
    '_register_continuation_reentry_on_open': WorkerMethodBindingSpec(method_name='_register_continuation_reentry_on_open', target_kind='instance', target_ref='_risk_evaluator', target_method='register_continuation_reentry_on_open'),
    '_register_continuation_reentry_on_profitable_close': WorkerMethodBindingSpec(method_name='_register_continuation_reentry_on_profitable_close', target_kind='instance', target_ref='_risk_evaluator', target_method='register_continuation_reentry_on_profitable_close'),
    '_repair_restored_timestamps': WorkerMethodBindingSpec(method_name='_repair_restored_timestamps', target_kind='instance', target_ref='_history_runtime', target_method='repair_restored_timestamps'),
    '_replace_latest_spread_sample': WorkerMethodBindingSpec(method_name='_replace_latest_spread_sample', target_kind='instance', target_ref='_risk_evaluator', target_method='replace_latest_spread_sample'),
    '_replace_latest_tick_sample': WorkerMethodBindingSpec(method_name='_replace_latest_tick_sample', target_kind='instance', target_ref='_history_runtime', target_method='replace_latest_tick_sample'),
    '_reset_broker_error_trackers': WorkerMethodBindingSpec(method_name='_reset_broker_error_trackers', target_kind='instance', target_ref='_recovery_manager', target_method='reset_broker_error_trackers'),
    '_resolve_mean_breakout_runtime_strategy': WorkerMethodBindingSpec(method_name='_resolve_mean_breakout_runtime_strategy', target_kind='instance', target_ref='_execution_quality_runtime', target_method='resolve_mean_breakout_runtime_strategy'),
    '_resolve_mode_scoped_strategy_param': WorkerMethodBindingSpec(method_name='_resolve_mode_scoped_strategy_param', target_kind='instance', target_ref='_risk_evaluator', target_method='resolve_mode_scoped_strategy_param'),
    '_resolve_multi_strategy_names': WorkerMethodBindingSpec(method_name='_resolve_multi_strategy_names', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='resolve_multi_strategy_names'),
    '_resolve_strategy_param_source_key': WorkerMethodBindingSpec(method_name='_resolve_strategy_param_source_key', target_kind='instance', target_ref='_config_runtime', target_method='resolve_strategy_param_source_key'),
    '_restore_price_history': WorkerMethodBindingSpec(method_name='_restore_price_history', target_kind='instance', target_ref='_history_runtime', target_method='restore_price_history'),
    '_restored_timestamps_need_repair': WorkerMethodBindingSpec(method_name='_restored_timestamps_need_repair', target_kind='instance', target_ref='_history_runtime', target_method='restored_timestamps_need_repair'),
    '_reversal_exit_armed': WorkerMethodBindingSpec(method_name='_reversal_exit_armed', target_kind='instance', target_ref='_protective_runtime', target_method='reversal_exit_armed'),
    '_reverse_signal_exit_reason': WorkerMethodBindingSpec(method_name='_reverse_signal_exit_reason', target_kind='instance', target_ref='_dynamic_exit_runtime', target_method='reverse_signal_exit_reason'),
    '_reverse_signal_exit_reason_from_signal': WorkerMethodBindingSpec(method_name='_reverse_signal_exit_reason_from_signal', target_kind='instance', target_ref='_dynamic_exit_runtime', target_method='reverse_signal_exit_reason_from_signal'),
    '_runner_preservation_state': WorkerMethodBindingSpec(method_name='_runner_preservation_state', target_kind='instance', target_ref='_protective_runtime', target_method='runner_preservation_state'),
    '_same_side_reentry_allows_open': WorkerMethodBindingSpec(method_name='_same_side_reentry_allows_open', target_kind='instance', target_ref='_risk_evaluator', target_method='same_side_reentry_allows_open'),
    '_save_state': WorkerMethodBindingSpec(method_name='_save_state', target_kind='instance', target_ref='_runtime_state_manager', target_method='save_state'),
    '_schedule_missing_position_reconciliation': WorkerMethodBindingSpec(method_name='_schedule_missing_position_reconciliation', target_kind='instance', target_ref='_reconcile_manager', target_method='schedule_missing_position_reconciliation'),
    '_seed_multi_strategy_normalizer_from_store': WorkerMethodBindingSpec(method_name='_seed_multi_strategy_normalizer_from_store', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='seed_multi_strategy_normalizer_from_store'),
    '_select_multi_strategy_risk_signal': WorkerMethodBindingSpec(method_name='_select_multi_strategy_risk_signal', target_kind='instance', target_ref='_multi_strategy_runtime', target_method='select_risk_signal'),
    '_session_exit_reason': WorkerMethodBindingSpec(method_name='_session_exit_reason', target_kind='instance', target_ref='_symbol_runtime', target_method='session_exit_reason'),
    '_set_position_trailing_override': WorkerMethodBindingSpec(method_name='_set_position_trailing_override', target_kind='instance', target_ref='_order_manager', target_method='set_position_trailing_override'),
    '_set_watchdog_blocking_operation_state': WorkerMethodBindingSpec(method_name='_set_watchdog_blocking_operation_state', target_kind='instance', target_ref='_lifecycle_manager', target_method='set_watchdog_blocking_operation_state'),
    '_should_close_position': WorkerMethodBindingSpec(method_name='_should_close_position', target_kind='instance', target_ref='_protective_runtime', target_method='should_close_position'),
    '_signal_atr_pips_for_entry': WorkerMethodBindingSpec(method_name='_signal_atr_pips_for_entry', target_kind='instance', target_ref='_execution_quality_runtime', target_method='signal_atr_pips_for_entry'),
    '_signal_execution_metrics': WorkerMethodBindingSpec(method_name='_signal_execution_metrics', target_kind='instance', target_ref='_execution_quality_runtime', target_method='signal_execution_metrics'),
    '_signal_fill_quality_strategy': WorkerMethodBindingSpec(method_name='_signal_fill_quality_strategy', target_kind='instance', target_ref='_execution_quality_runtime', target_method='signal_fill_quality_strategy'),
    '_signal_implied_trend_side': WorkerMethodBindingSpec(method_name='_signal_implied_trend_side', target_kind='instance', target_ref='_dynamic_exit_runtime', target_method='signal_implied_trend_side'),
    '_signal_management_family': WorkerMethodBindingSpec(method_name='_signal_management_family', target_kind='instance', target_ref='_risk_evaluator', target_method='signal_management_family'),
    '_slippage_pips': WorkerMethodBindingSpec(method_name='_slippage_pips', target_kind='instance', target_ref='_execution_quality_runtime', target_method='slippage_pips'),
    '_spread_filter_metrics': WorkerMethodBindingSpec(method_name='_spread_filter_metrics', target_kind='instance', target_ref='_risk_evaluator', target_method='spread_filter_metrics'),
    '_spread_buffer_snapshot': WorkerMethodBindingSpec(method_name='_spread_buffer_snapshot', target_kind='instance', target_ref='_risk_evaluator', target_method='spread_buffer_snapshot'),
    '_spread_in_pips': WorkerMethodBindingSpec(method_name='_spread_in_pips', target_kind='instance', target_ref='_risk_evaluator', target_method='spread_in_pips'),
    '_spread_pct_allows_open': WorkerMethodBindingSpec(method_name='_spread_pct_allows_open', target_kind='instance', target_ref='_risk_evaluator', target_method='spread_pct_allows_open'),
    '_spread_pct_limit': WorkerMethodBindingSpec(method_name='_spread_pct_limit', target_kind='instance', target_ref='_risk_evaluator', target_method='spread_pct_limit'),
    '_stale_entry_history_allows_open': WorkerMethodBindingSpec(method_name='_stale_entry_history_allows_open', target_kind='instance', target_ref='_history_runtime', target_method='stale_entry_history_allows_open'),
    '_stale_loser_exit_allowed': WorkerMethodBindingSpec(method_name='_stale_loser_exit_allowed', target_kind='instance', target_ref='_protective_runtime', target_method='stale_loser_exit_allowed'),
    '_strategy_bool_param': WorkerMethodBindingSpec(method_name='_strategy_bool_param', target_kind='instance', target_ref='_strategy_param_runtime', target_method='strategy_bool_param'),
    '_strategy_choice_param': WorkerMethodBindingSpec(method_name='_strategy_choice_param', target_kind='instance', target_ref='_strategy_param_runtime', target_method='strategy_choice_param'),
    '_strategy_dynamic_exit_reason': WorkerMethodBindingSpec(method_name='_strategy_dynamic_exit_reason', target_kind='instance', target_ref='_dynamic_exit_runtime', target_method='strategy_dynamic_exit_reason'),
    '_strategy_exit_signal': WorkerMethodBindingSpec(method_name='_strategy_exit_signal', target_kind='instance', target_ref='_signal_runtime', target_method='strategy_exit_signal'),
    '_strategy_float_param': WorkerMethodBindingSpec(method_name='_strategy_float_param', target_kind='instance', target_ref='_strategy_param_runtime', target_method='strategy_float_param'),
    '_strategy_float_param_for_label': WorkerMethodBindingSpec(method_name='_strategy_float_param_for_label', target_kind='instance', target_ref='_strategy_param_runtime', target_method='strategy_float_param_for_label'),
    '_strategy_history_context_limit': WorkerMethodBindingSpec(method_name='_strategy_history_context_limit', target_kind='instance', target_ref='_history_runtime', target_method='strategy_history_context_limit'),
    '_strategy_param_key': WorkerMethodBindingSpec(method_name='_strategy_param_key', target_kind='instance', target_ref='_strategy_param_runtime', target_method='strategy_param_key'),
    '_strategy_param_namespace_label': WorkerMethodBindingSpec(method_name='_strategy_param_namespace_label', target_kind='instance', target_ref='_strategy_param_runtime', target_method='strategy_param_namespace_label'),
    '_strategy_symbol_float_map_param': WorkerMethodBindingSpec(method_name='_strategy_symbol_float_map_param', target_kind='instance', target_ref='_strategy_param_runtime', target_method='strategy_symbol_float_map_param'),
    '_stream_health_allows_open': WorkerMethodBindingSpec(method_name='_stream_health_allows_open', target_kind='instance', target_ref='_health_monitor', target_method='stream_health_allows_open'),
    '_stream_health_entry_block_reason': WorkerMethodBindingSpec(method_name='_stream_health_entry_block_reason', target_kind='instance', target_ref='_health_monitor', target_method='stream_health_entry_block_reason'),
    '_stream_health_payload': WorkerMethodBindingSpec(method_name='_stream_health_payload', target_kind='instance', target_ref='_health_monitor', target_method='stream_health_payload'),
    '_sync_allowance_backoff_from_connectivity_probe': WorkerMethodBindingSpec(method_name='_sync_allowance_backoff_from_connectivity_probe', target_kind='instance', target_ref='_recovery_manager', target_method='sync_allowance_backoff_from_connectivity_probe'),
    '_sync_local_symbol_lot_min_from_broker_error': WorkerMethodBindingSpec(method_name='_sync_local_symbol_lot_min_from_broker_error', target_kind='instance', target_ref='_recovery_manager', target_method='sync_local_symbol_lot_min_from_broker_error'),
    '_sync_strategy_runtime_pip_size': WorkerMethodBindingSpec(method_name='_sync_strategy_runtime_pip_size', target_kind='instance', target_ref='_symbol_spec_runtime', target_method='sync_strategy_runtime_pip_size'),
    '_synthetic_exit_policy_from_signal': WorkerMethodBindingSpec(method_name='_synthetic_exit_policy_from_signal', target_kind='instance', target_ref='_signal_runtime', target_method='synthetic_exit_policy_from_signal'),
    '_trailing_breakeven_offset_for_symbol_pips': WorkerMethodBindingSpec(method_name='_trailing_breakeven_offset_for_symbol_pips', target_kind='instance', target_ref='_symbol_runtime', target_method='trailing_breakeven_offset_for_symbol_pips'),
    '_trailing_candidate_stop': WorkerMethodBindingSpec(method_name='_trailing_candidate_stop', target_kind='instance', target_ref='_trailing_runtime', target_method='trailing_candidate_stop'),
    '_update_position_peak_adverse_pips': WorkerMethodBindingSpec(method_name='_update_position_peak_adverse_pips', target_kind='instance', target_ref='_protective_runtime', target_method='update_position_peak_adverse_pips'),
    '_update_position_peak_favorable_pips': WorkerMethodBindingSpec(method_name='_update_position_peak_favorable_pips', target_kind='instance', target_ref='_protective_runtime', target_method='update_position_peak_favorable_pips'),
    '_validate_broker_close_sync': WorkerMethodBindingSpec(method_name='_validate_broker_close_sync', target_kind='instance', target_ref='_reconcile_manager', target_method='validate_broker_close_sync'),
    '_wait_with_state_heartbeat': WorkerMethodBindingSpec(method_name='_wait_with_state_heartbeat', target_kind='instance', target_ref='_recovery_manager', target_method='wait_with_state_heartbeat'),
    '_watchdog_blocking_operation': WorkerMethodBindingSpec(method_name='_watchdog_blocking_operation', target_kind='instance', target_ref='_lifecycle_manager', target_method='watchdog_blocking_operation'),
    '_worker_lease_allows_trading': WorkerMethodBindingSpec(method_name='_worker_lease_allows_trading', target_kind='instance', target_ref='_lifecycle_manager', target_method='worker_lease_allows_trading'),
    'watchdog_blocking_operation_status': WorkerMethodBindingSpec(method_name='watchdog_blocking_operation_status', target_kind='instance', target_ref='_lifecycle_manager', target_method='watchdog_blocking_operation_status'),
    '_allowance_backoff_kind': WorkerMethodBindingSpec(method_name='_allowance_backoff_kind', target_kind='class', target_ref='WorkerRecoveryManager', target_method='allowance_backoff_kind'),
    '_broker_min_stop_distance_price_for_spec': WorkerMethodBindingSpec(method_name='_broker_min_stop_distance_price_for_spec', target_kind='class', target_ref='WorkerPriceGuardRuntime', target_method='broker_min_stop_distance_price_for_spec'),
    '_broker_supports_force_refresh_fallback': WorkerMethodBindingSpec(method_name='_broker_supports_force_refresh_fallback', target_kind='class', target_ref='WorkerSymbolSpecRuntime', target_method='broker_supports_force_refresh_fallback'),
    '_broker_sync_has_close_evidence': WorkerMethodBindingSpec(method_name='_broker_sync_has_close_evidence', target_kind='class', target_ref='WorkerReconcileManager', target_method='broker_sync_has_close_evidence'),
    '_broker_sync_has_factual_close_details': WorkerMethodBindingSpec(method_name='_broker_sync_has_factual_close_details', target_kind='class', target_ref='WorkerReconcileManager', target_method='broker_sync_has_factual_close_details'),
    '_broker_sync_indicates_position_missing': WorkerMethodBindingSpec(method_name='_broker_sync_indicates_position_missing', target_kind='class', target_ref='WorkerReconcileManager', target_method='broker_sync_indicates_position_missing'),
    '_broker_sync_is_partial_close': WorkerMethodBindingSpec(method_name='_broker_sync_is_partial_close', target_kind='class', target_ref='WorkerReconcileManager', target_method='broker_sync_is_partial_close'),
    '_bucket_start_ts': WorkerMethodBindingSpec(method_name='_bucket_start_ts', target_kind='class', target_ref='WorkerHistoryRuntime', target_method='bucket_start_ts'),
    '_build_magic_comment': WorkerMethodBindingSpec(method_name='_build_magic_comment', target_kind='class', target_ref='WorkerOrderManager', target_method='build_magic_comment'),
    '_coerce_positive_finite': WorkerMethodBindingSpec(method_name='_coerce_positive_finite', target_kind='class', target_ref='WorkerValueRuntime', target_method='coerce_positive_finite'),
    '_coerce_positive_volume': WorkerMethodBindingSpec(method_name='_coerce_positive_volume', target_kind='class', target_ref='WorkerHistoryRuntime', target_method='coerce_positive_volume'),
    '_confidence_value': WorkerMethodBindingSpec(method_name='_confidence_value', target_kind='class', target_ref='WorkerSignalRuntime', target_method='confidence_value'),
    '_context_last_price': WorkerMethodBindingSpec(method_name='_context_last_price', target_kind='class', target_ref='WorkerSignalRuntime', target_method='context_last_price'),
    '_cooldown_outcome_from_pnl': WorkerMethodBindingSpec(method_name='_cooldown_outcome_from_pnl', target_kind='class', target_ref='WorkerRiskEvaluator', target_method='cooldown_outcome_from_pnl'),
    '_current_volume_from_tick': WorkerMethodBindingSpec(method_name='_current_volume_from_tick', target_kind='class', target_ref='WorkerHistoryRuntime', target_method='current_volume_from_tick'),
    '_dynamic_exit_reason': WorkerMethodBindingSpec(method_name='_dynamic_exit_reason', target_kind='class', target_ref='WorkerDynamicExitRuntime', target_method='dynamic_exit_reason'),
    '_dynamic_exit_scope': WorkerMethodBindingSpec(method_name='_dynamic_exit_scope', target_kind='class', target_ref='WorkerDynamicExitRuntime', target_method='dynamic_exit_scope'),
    '_epic_variant_text': WorkerMethodBindingSpec(method_name='_epic_variant_text', target_kind='class', target_ref='WorkerSymbolRuntime', target_method='epic_variant_text'),
    '_execution_quality_penalty_from_metrics': WorkerMethodBindingSpec(method_name='_execution_quality_penalty_from_metrics', target_kind='class', target_ref='WorkerExecutionQualityRuntime', target_method='execution_quality_penalty_from_metrics'),
    '_extract_allowance_backoff_remaining_sec': WorkerMethodBindingSpec(method_name='_extract_allowance_backoff_remaining_sec', target_kind='class', target_ref='WorkerRecoveryManager', target_method='extract_allowance_backoff_remaining_sec'),
    '_extract_broker_minimum_lot_from_error': WorkerMethodBindingSpec(method_name='_extract_broker_minimum_lot_from_error', target_kind='class', target_ref='WorkerRecoveryManager', target_method='extract_broker_minimum_lot_from_error'),
    '_hold_invalidation_reason': WorkerMethodBindingSpec(method_name='_hold_invalidation_reason', target_kind='class', target_ref='WorkerDynamicExitRuntime', target_method='hold_invalidation_reason'),
    '_is_affordability_risk_reject_reason': WorkerMethodBindingSpec(method_name='_is_affordability_risk_reject_reason', target_kind='class', target_ref='WorkerEntryPlanner', target_method='is_affordability_risk_reject_reason'),
    '_is_allowance_backoff_error': WorkerMethodBindingSpec(method_name='_is_allowance_backoff_error', target_kind='class', target_ref='WorkerRecoveryManager', target_method='is_allowance_backoff_error'),
    '_is_broker_position_missing_error': WorkerMethodBindingSpec(method_name='_is_broker_position_missing_error', target_kind='class', target_ref='WorkerReconcileManager', target_method='is_broker_position_missing_error'),
    '_is_compact_json_value': WorkerMethodBindingSpec(method_name='_is_compact_json_value', target_kind='class', target_ref='WorkerDiagnosticsRuntime', target_method='is_compact_json_value'),
    '_is_connectivity_dispatch_timeout_non_blocking': WorkerMethodBindingSpec(method_name='_is_connectivity_dispatch_timeout_non_blocking', target_kind='class', target_ref='WorkerHealthMonitor', target_method='is_connectivity_dispatch_timeout_non_blocking'),
    '_is_connectivity_high_latency_non_blocking': WorkerMethodBindingSpec(method_name='_is_connectivity_high_latency_non_blocking', target_kind='class', target_ref='WorkerHealthMonitor', target_method='is_connectivity_high_latency_non_blocking'),
    '_is_continuation_trend_signal': WorkerMethodBindingSpec(method_name='_is_continuation_trend_signal', target_kind='class', target_ref='WorkerRiskEvaluator', target_method='is_continuation_trend_signal'),
    '_is_cross_trend_signal': WorkerMethodBindingSpec(method_name='_is_cross_trend_signal', target_kind='class', target_ref='WorkerRiskEvaluator', target_method='is_cross_trend_signal'),
    '_is_db_first_symbol_spec_cache_miss_error': WorkerMethodBindingSpec(method_name='_is_db_first_symbol_spec_cache_miss_error', target_kind='class', target_ref='WorkerRecoveryManager', target_method='is_db_first_symbol_spec_cache_miss_error'),
    '_is_db_first_tick_cache_miss_error': WorkerMethodBindingSpec(method_name='_is_db_first_tick_cache_miss_error', target_kind='class', target_ref='WorkerRecoveryManager', target_method='is_db_first_tick_cache_miss_error'),
    '_is_epic_unavailable_error': WorkerMethodBindingSpec(method_name='_is_epic_unavailable_error', target_kind='class', target_ref='WorkerRecoveryManager', target_method='is_epic_unavailable_error'),
    '_is_json_scalar': WorkerMethodBindingSpec(method_name='_is_json_scalar', target_kind='class', target_ref='WorkerDiagnosticsRuntime', target_method='is_json_scalar'),
    '_is_market_closed_close_error': WorkerMethodBindingSpec(method_name='_is_market_closed_close_error', target_kind='class', target_ref='WorkerOrderManager', target_method='is_market_closed_close_error'),
    '_is_open_confirm_timeout_pending_recovery_error': WorkerMethodBindingSpec(method_name='_is_open_confirm_timeout_pending_recovery_error', target_kind='class', target_ref='WorkerRecoveryManager', target_method='is_open_confirm_timeout_pending_recovery_error'),
    '_is_open_reject_error': WorkerMethodBindingSpec(method_name='_is_open_reject_error', target_kind='class', target_ref='WorkerRiskEvaluator', target_method='is_open_reject_error'),
    '_is_quote_unavailable_error': WorkerMethodBindingSpec(method_name='_is_quote_unavailable_error', target_kind='class', target_ref='WorkerRecoveryManager', target_method='is_quote_unavailable_error'),
    '_is_retryable_close_error': WorkerMethodBindingSpec(method_name='_is_retryable_close_error', target_kind='class', target_ref='WorkerOrderManager', target_method='is_retryable_close_error'),
    '_merge_reason_lists': WorkerMethodBindingSpec(method_name='_merge_reason_lists', target_kind='class', target_ref='WorkerExecutionQualityRuntime', target_method='merge_reason_lists'),
    '_metadata_bool': WorkerMethodBindingSpec(method_name='_metadata_bool', target_kind='class', target_ref='WorkerExecutionQualityRuntime', target_method='metadata_bool'),
    '_metadata_number': WorkerMethodBindingSpec(method_name='_metadata_number', target_kind='class', target_ref='WorkerExecutionQualityRuntime', target_method='metadata_number'),
    '_metadata_text': WorkerMethodBindingSpec(method_name='_metadata_text', target_kind='class', target_ref='WorkerExecutionQualityRuntime', target_method='metadata_text'),
    '_metadata_trailing_distance_pips': WorkerMethodBindingSpec(method_name='_metadata_trailing_distance_pips', target_kind='class', target_ref='WorkerSignalRuntime', target_method='metadata_trailing_distance_pips'),
    '_multi_strategy_confidence': WorkerMethodBindingSpec(method_name='_multi_strategy_confidence', target_kind='class', target_ref='WorkerMultiStrategyRuntime', target_method='confidence'),
    '_multi_strategy_directional_summary': WorkerMethodBindingSpec(method_name='_multi_strategy_directional_summary', target_kind='class', target_ref='WorkerMultiStrategyRuntime', target_method='directional_summary'),
    '_normalize_currency_code': WorkerMethodBindingSpec(method_name='_normalize_currency_code', target_kind='class', target_ref='WorkerValueRuntime', target_method='normalize_currency_code'),
    '_normalize_deal_reference': WorkerMethodBindingSpec(method_name='_normalize_deal_reference', target_kind='class', target_ref='WorkerPriceRuntime', target_method='normalize_deal_reference'),
    '_normalize_price_ceil_for_spec': WorkerMethodBindingSpec(method_name='_normalize_price_ceil_for_spec', target_kind='class', target_ref='WorkerPriceRuntime', target_method='normalize_price_ceil_for_spec'),
    '_normalize_price_floor_for_spec': WorkerMethodBindingSpec(method_name='_normalize_price_floor_for_spec', target_kind='class', target_ref='WorkerPriceRuntime', target_method='normalize_price_floor_for_spec'),
    '_normalize_price_for_spec': WorkerMethodBindingSpec(method_name='_normalize_price_for_spec', target_kind='class', target_ref='WorkerPriceRuntime', target_method='normalize_price_for_spec'),
    '_normalize_strategy_label': WorkerMethodBindingSpec(method_name='_normalize_strategy_label', target_kind='class', target_ref='WorkerConfigRuntime', target_method='normalize_strategy_label'),
    '_normalize_strategy_symbols_scope': WorkerMethodBindingSpec(method_name='_normalize_strategy_symbols_scope', target_kind='class', target_ref='WorkerConfigRuntime', target_method='normalize_strategy_symbols_scope'),
    '_parse_strategy_names': WorkerMethodBindingSpec(method_name='_parse_strategy_names', target_kind='class', target_ref='WorkerConfigRuntime', target_method='parse_strategy_names'),
    '_parse_symbol_float_map': WorkerMethodBindingSpec(method_name='_parse_symbol_float_map', target_kind='class', target_ref='WorkerConfigRuntime', target_method='parse_symbol_float_map'),
    '_parse_weight_map': WorkerMethodBindingSpec(method_name='_parse_weight_map', target_kind='class', target_ref='WorkerConfigRuntime', target_method='parse_weight_map'),
    '_prefer_tighter_trailing_candidate': WorkerMethodBindingSpec(method_name='_prefer_tighter_trailing_candidate', target_kind='class', target_ref='WorkerTrailingRuntime', target_method='prefer_tighter_trailing_candidate'),
    '_raw_broker_contract_value': WorkerMethodBindingSpec(method_name='_raw_broker_contract_value', target_kind='class', target_ref='WorkerEntryPlanner', target_method='raw_broker_contract_value'),
    '_safe_float': WorkerMethodBindingSpec(method_name='_safe_float', target_kind='class', target_ref='WorkerValueRuntime', target_method='safe_float'),
    '_signal_hold_state': WorkerMethodBindingSpec(method_name='_signal_hold_state', target_kind='class', target_ref='WorkerSignalRuntime', target_method='signal_hold_state'),
    '_signal_metadata': WorkerMethodBindingSpec(method_name='_signal_metadata', target_kind='class', target_ref='WorkerSignalRuntime', target_method='signal_metadata'),
    '_signal_target_qty_lots': WorkerMethodBindingSpec(method_name='_signal_target_qty_lots', target_kind='class', target_ref='WorkerSignalRuntime', target_method='signal_target_qty_lots'),
    '_signal_timeframe_hint_sec': WorkerMethodBindingSpec(method_name='_signal_timeframe_hint_sec', target_kind='class', target_ref='WorkerHistoryRuntime', target_method='signal_timeframe_hint_sec'),
    '_smoothstep01': WorkerMethodBindingSpec(method_name='_smoothstep01', target_kind='class', target_ref='WorkerTrailingRuntime', target_method='smoothstep01'),
    '_spec_epic': WorkerMethodBindingSpec(method_name='_spec_epic', target_kind='class', target_ref='WorkerSymbolRuntime', target_method='spec_epic'),
    '_spec_epic_variant': WorkerMethodBindingSpec(method_name='_spec_epic_variant', target_kind='class', target_ref='WorkerSymbolRuntime', target_method='spec_epic_variant'),
    '_spread_in_pct': WorkerMethodBindingSpec(method_name='_spread_in_pct', target_kind='class', target_ref='WorkerRiskEvaluator', target_method='spread_in_pct'),
    '_strategy_candle_timeframe': WorkerMethodBindingSpec(method_name='_strategy_candle_timeframe', target_kind='class', target_ref='WorkerHistoryRuntime', target_method='strategy_candle_timeframe'),
    '_stream_reason_matches_entry_block': WorkerMethodBindingSpec(method_name='_stream_reason_matches_entry_block', target_kind='class', target_ref='WorkerHealthMonitor', target_method='stream_reason_matches_entry_block'),
    '_symbol_override_float': WorkerMethodBindingSpec(method_name='_symbol_override_float', target_kind='class', target_ref='WorkerStrategyParamRuntime', target_method='symbol_override_float'),
    '_synthetic_exit_reason_for_intent': WorkerMethodBindingSpec(method_name='_synthetic_exit_reason_for_intent', target_kind='class', target_ref='WorkerSignalRuntime', target_method='synthetic_exit_reason_for_intent'),
    '_tick_freshness_timestamp_sec': WorkerMethodBindingSpec(method_name='_tick_freshness_timestamp_sec', target_kind='class', target_ref='WorkerHistoryRuntime', target_method='tick_freshness_timestamp_sec'),
    '_trend_signal_direction': WorkerMethodBindingSpec(method_name='_trend_signal_direction', target_kind='class', target_ref='WorkerRiskEvaluator', target_method='trend_signal_direction'),
    '_trend_signal_from_signal': WorkerMethodBindingSpec(method_name='_trend_signal_from_signal', target_kind='class', target_ref='WorkerRiskEvaluator', target_method='trend_signal_from_signal'),
}


def bound_worker_method_names() -> tuple[str, ...]:
    return tuple(_METHOD_SPECS)


def resolve_bound_worker_method(worker, name: str) -> Callable:
    spec = _METHOD_SPECS.get(name)
    if spec is None:
        raise AttributeError(name)
    if spec.target_kind == 'instance':
        delegate = getattr(worker, spec.target_ref)
        target = getattr(delegate, spec.target_method)
    else:
        target_cls = _CLASS_TARGETS[spec.target_ref]
        target = getattr(target_cls, spec.target_method)

    def _bound(*args, **kwargs):
        return target(*args, **kwargs)

    _bound.__name__ = name
    _bound.__qualname__ = f"SymbolWorker.{name}"
    return _bound
